### ISSUE TITLE
Output directory option

### ISSUE THREAD

**Issue by fgypas** [biocompibens/ALFA#2]
Hi

I installed alfa via conda (version 1.1.0) and started using it. It works fine, but I have an issue when running a command like the following:

```
alfa \
-g results/annotation/alfa_genome_index \
--bam results/sample/bowtie/alignment.sorted.bam sample \
-d 2 \
--keep_ambiguous \
--processors 8 \
--strandness forward
--pdf results/sample/plots/alfa_aligment_statistics/alfa_aligment_statistics.pdf \
--temp_dir results/sample/plots/alfa_aligment_statistics
```

The problem is that apart from the "alfa_aligment_statistics.Biotypes.pdf" and "alfa_aligment_statistics.Categories.pdf" under the plots directory it also creates some files in the current working directory:

- sample.ALFA_feature_counts.tsv
- sample.minus.bedgraph
- sample.plus.bedgraph

Can you please add an option to provide an output directory that all files are written?

Thank in advance
Foivos

**Comment by mbahin** [comment]
Hi Foivos,

Thanks for your message.
I'll try to work on that this week and let you know when I have something satisfying.

Cheers,
Mathieu

**Comment by mbahin** [comment]
Hi Foivos,

I updated the repo, I think it's ok now with the "-o" options.
Let me know if you have bugs.

Cheers,
Mathieu

**Comment by fgypas** [comment]
@mbahin 

Hi Mathieu

I tried it and it works fine. Thanks a lot for the quick fix.
I close the issue.

Best
Foivos
