### ISSUE TITLE
Quick start tool installation failing 

### ISSUE THREAD

**Issue by LoransM** [biocompibens/ALFA#5]
Hello,

I have used git clone https://github.com/biocompibens/ALFA to install the program, but when trying to test the tool installation   according to the quick start guide, I get following error:

rna2@d33502:~/ALFA/Quick_start$ python alfa.py -a quick_start.gtf --chr_len quick_start.chr_len.txt -g quick_start --bam quick_start.bam quick_start
  File "alfa.py", line 171
    print("Warning: chromosome '" + chrom + "' of the chromosome lengths file does not match any chromosome name in the GTF file provided and was ignored.", file=sys.stderr)
                                                                                                                                                                 ^
SyntaxError: invalid syntax

Can anyone please assist me?
Thanks

**Comment by mbahin** [comment]
Hi,

The first thing that comes to my mind is that maybe you're trying to run ALFA with some version of Python 2 though it has to run with Python 3.
Let me know if it was the source of the problem.

Cheers,
Mathieu

**Comment by LoransM** [comment]
Hi Mathieu,
Now I get following issue when running with Python3:

python3 alfa.py -a quick_start.gtf --chr_len quick_start.chr_len.txt -g quick_start --bam quick_start.bam quick_start
Traceback (most recent call last):
 File “alfa.py”, line 14, in <module>
  import pysam
ModuleNotFoundError: No module named ‘pysam’

Although pysam is installed and up to date.

Marie Lorans
PhD fellow
Aarhus University
Institute of Molecular Biology and Genetics
C.F. Møllers Alle 3
8000 Aarhus
Denmark
Ph: +4531717672

**Comment by mbahin** [comment]
Hi Mary,

From the message you get, I strongly doubt that the pysam lib is installed.
Maybe it's installed but not for the Python you're calling with ALFA. You could try to run the same Python (typing "python3" in a terminal probably) and do "import pysam" to check.

Cheers,
Mathieu

**Comment by LoransM** [comment]
That worked! Thanks so much!

Marie Lorans
PhD fellow
Aarhus University
Institute of Molecular Biology and Genetics
C.F. Møllers Alle 3
8000 Aarhus
Denmark
Ph: +4531717672
